/**
 * @file types.hpp
 *
 */
#ifndef TYPES_HPP
#define TYPES_HPP

#include <cstdint>

enum enOnfootKeys : uint8_t
{
    LEFT_RIGHT = 0,
    FORWARD_BACKWARD,
    /* ... */
    AIM_WEAPON = 6,
    /* ... */
    JUMP = 14,
    /* ... */
    SPRINT = 16,
    FIRE,
    WALK = 21
};

enum enWeaponId
{
    WEAPON_UNARMED = 0,
    WEAPON_BRASSKNUCKLE = 1,
    WEAPON_GOLFCLUB = 2,
    WEAPON_NIGHTSTICK = 3,
    WEAPON_KNIFE = 4,
    WEAPON_BASEBALLBAT = 5,
    WEAPON_SHOVEL = 6,
    WEAPON_POOLCUE = 7,
    WEAPON_KATANA = 8,
    WEAPON_CHAINSAW = 9,
    WEAPON_DILDO1 = 10,
    WEAPON_DILDO2 = 11,
    WEAPON_VIBE1 = 12,
    WEAPON_VIBE2 = 13,
    WEAPON_FLOWERS = 14,
    WEAPON_CANE = 15,
    WEAPON_GRENADE = 16,
    WEAPON_TEARGAS = 17,
    WEAPON_MOLOTOV = 18,
    WEAPON_ROCKET = 19,
    WEAPON_ROCKET_HS = 20,
    WEAPON_FREEFALL_BOMB = 21,
    WEAPON_PISTOL = 22,
    WEAPON_PISTOL_SILENCED = 23,
    WEAPON_DESERT_EAGLE = 24,
    WEAPON_SHOTGUN = 25,
    WEAPON_SAWNOFF = 26,
    WEAPON_SPAS12 = 27,
    WEAPON_MICRO_UZI = 28,
    WEAPON_MP5 = 29,
    WEAPON_AK47 = 30,
    WEAPON_M4 = 31,
    WEAPON_TEC9 = 32,
    WEAPON_COUNTRYRIFLE = 33,
    WEAPON_SNIPERRIFLE = 34,
    WEAPON_RLAUNCHER = 35,
    WEAPON_RLAUNCHER_HS = 36,
    WEAPON_FTHROWER = 37,
    WEAPON_MINIGUN = 38,
    WEAPON_SATCHEL_CHARGE = 39,
    WEAPON_DETONATOR = 40,
    WEAPON_SPRAYCAN = 41,
    WEAPON_EXTINGUISHER = 42,
    WEAPON_CAMERA = 43,
    WEAPON_NIGHTVISION = 44,
    WEAPON_INFRARED = 45,
    WEAPON_PARACHUTE = 46,
    WEAPON_UNUSED = 47,
    WEAPON_ARMOUR = 48,
    WEAPON_FLARE = 58
};

#endif /* TYPES_HPP */
